version: "3.8"

services:
  flask-app:
    image: juanantpineda/flask-app:latest  # Usa el nombre de la imagen que creaste
    container_name: flask-app
    ports:
      - "5002:5002"  # Mapea el puerto del contenedor al host
    environment:
      - NOMBRE=Juan-Antonio-Pineda-Amador  # Define una variable de entorno
    volumes:
      - contador_data:/usr/share/app/  # Mantiene el archivo contador.txt persistente
    restart: unless-stopped  # Reinicia el contenedor si falla

volumes:
  contador_data: